name: Build connector

on:
  workflow_dispatch:
    inputs:
      metabase-version:
        required: true
        description: Metabase version to compile with
        type: string
        default: v0.46.2

jobs:
  build-connector:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Metabase Code"
        uses: actions/checkout@v2
        with:
          repository: metabase/metabase
          ref: ${{ github.event.inputs.metabase-version }}
          path: metabase

      - name: "Checkout Driver"
        uses: actions/checkout@v2
        with:
          path: metabase-guandata-driver

      - name: "Checkout Guandata JDBC Driver"
        uses: actions/checkout@v2
        with:
          repository: Baoqi/guandata-jdbc-driver
          path: guandata-jdbc-driver

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build with Maven
        run: cd guandata-jdbc-driver && mvn --batch-mode clean package -DskipTests && mv target/guandata-jdbc-2.0.0-SNAPSHOT.jar ../metabase-guandata-driver/jdbc_driver/

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.7
        if: steps.cache-metabase-jar.outputs.cache-hit != 'true'
        with:
          # Install just one or all simultaneously
          cli: 'latest' # Clojure CLI based on tools.deps

      - name: "Run build.sh"
        run: |
          cd metabase-guandata-driver && ./build.sh

      - name: Upload resulting jar file
        uses: actions/upload-artifact@v2
        with:
          name: guandata.metabase-driver.jar
          path: metabase-guandata-driver/target/guandata.metabase-driver.jar
